#!/bin/sh
chmod +x script/deploy
ssh ec2-user@ip-172-31-29-194 <<EOF
    cd ~/ApplicationTrackerBackend
    git pull origin mongodb-atlas

    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF